# Generated by Django 4.0.4 on 2022-04-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('U', 'User'), ('L', 'Team Leader'), ('M', 'Team Member')], default='U', max_length=1),
        ),
    ]
